name: Test

on:
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - 'infrastructure/images'
      - '.github/workflows/test.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.8.5
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      MS_365_VMS_VM_SIZE: Standard_D2s_v3
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2022-ad-westeurope-000000
      MS_365_VMS_LOCATION: westeurope
      MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
      MS_365_VMS_PACKER_VM_NAME: swaz${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - run: cd infrastructure/images
      - run: packer build -only azure-arm win2022-ad.json
  clean:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:2.16.0
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2022-ad-westeurope-000000
      MS_365_VMS_LOCATION: westeurope
      MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
    steps:
      - uses: actions/checkout@v2
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az image delete --subscription $ARM_SUBSCRIPTION_ID -g $MS_365_VMS_IMAGE_RG_NAME -n $MS_365_VMS_IMAGE_NAME