name: Test Stacks Only

on:
  workflow_dispatch:
  push: 
    paths:
      - 'infrastructure/stacks'
      - '.github/workflows/test-stacks-only.yaml'
      - '!infrastructure/images'
      - '!.github/workflows/test.yaml'
jobs:
  provision-ad2019_crm:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.11.15
    env:
      TF_VAR_ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      TF_VAR_ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      TF_VAR_MS_365_VMS_LOCATION: westeurope
      TF_VAR_MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
      TF_VAR_MS_365_VMS_VM_NAME_SPEC: swaz%s
      TF_VAR_MS_365_VMS_WIN2019_AD_IMAGE_ID: /subscriptions/86fab581-914f-4c91-be92-9a5d70691d54/resourceGroups/CommonRGWestEurope/providers/Microsoft.Compute/images/ms-365-vms-win2019-ad-westeurope-000000
      TF_VAR_MS_365_VMS_WIN2019_AD_VM_SIZE: Standard_B2s
      TF_VAR_MS_365_VMS_DOMAIN_NAME: c0nt0s00.local
      TF_VAR_MS_365_VMS_VM_ADMIN_PASSWORD: ${{ secrets.MS_365_VMS_VM_ADMIN_PASSWORD }}
      TF_VAR_MS_365_VMS_DOMAIN_ADMIN_PASSWORD: ${{ secrets.MS_365_VMS_DOMAIN_ADMIN_PASSWORD }}
      TF_VAR_RS_SERVICE_PASSWORD: ${{ secrets.RS_SERVICE_PASSWORD }}
      TF_VAR_CRM_TEST_1_PASSWORD: ${{ secrets.CRM_TEST_1_PASSWORD }}
      TF_VAR_CRM_TEST_2_PASSWORD: ${{ secrets.CRM_TEST_2_PASSWORD }}
      TF_VAR_CRM_INSTALL_PASSWORD: ${{ secrets.CRM_INSTALL_PASSWORD }}
      TF_VAR_CRM_SERVICE_PASSWORD: ${{ secrets.CRM_SERVICE_PASSWORD }}
      TF_VAR_CRM_DEPLOYMENT_SERVICE_PASSWORD: ${{ secrets.CRM_DEPLOYMENT_SERVICE_PASSWORD }}
      TF_VAR_CRM_SANDBOX_SERVICE_PASSWORD: ${{ secrets.CRM_SANDBOX_SERVICE_PASSWORD }}
      TF_VAR_CRM_VSS_WRITER_PASSWORD: ${{ secrets.CRM_VSS_WRITER_PASSWORD }}
      TF_VAR_CRM_ASYNC_SERVICE_PASSWORD: ${{ secrets.CRM_ASYNC_SERVICE_PASSWORD }}
      TF_VAR_CRM_MONITORING_SERVICE_PASSWORD: ${{ secrets.CRM_MONITORING_SERVICE_PASSWORD }}
      TF_VAR_MS_365_VMS_STACK_INSTANCE_ID: ms-365-vms-ad2019_crm-test-00
      TF_VAR_MS_365_VMS_DNS_PREFIX: ms-365-vms-ad2019_crm-test-00-
    steps:
      - uses: actions/checkout@v3
      - run: cd infrastructure/stacks/azure/ad2019_crm; terraform init
      - run: cd infrastructure/stacks/azure/ad2019_crm; terraform workspace new $TF_VAR_MS_365_VMS_STACK_INSTANCE_ID
      - run: cd infrastructure/stacks/azure/ad2019_crm; terraform apply -auto-approve
  clean-ad2019_crm:
    if: ${{ always() }}
    needs: provision-ad2019_crm
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:2.16.0
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az group delete --subscription $ARM_SUBSCRIPTION_ID -n ms-365-vms-ad2019_crm-test-00 -y
