name: Test CRM

on:
  workflow_dispatch:
  push: 
    paths:
      - '.github/workflows/test-crm.yaml'
jobs:
  build-win2022-ad-sql2022-rs2019-crm-wp:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.8.7
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      MS_365_VMS_VM_SIZE: Standard_D4s_v5
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2022-ad-sql2022-rs2019-crm-wp-westeurope-000000
      MS_365_VMS_LOCATION: westeurope
      MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
      MS_365_VMS_PACKER_VM_NAME: swaz11${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - run: cd infrastructure/images; packer build -only azure-arm.azure00 -force win2022-ad-sql2022-rs2019-crm-wp.pkr.hcl
  build-win2016-ad-sql2016-rs-crm-wp:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.8.7
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      MS_365_VMS_VM_SIZE: Standard_D4s_v5
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2016-ad-sql2016-rs-crm-wp-westeurope-000000
      MS_365_VMS_LOCATION: westeurope
      MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
      MS_365_VMS_PACKER_VM_NAME: swaz11${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - run: cd infrastructure/images; packer build -only azure-arm.azure00 -force win2016-ad-sql2016-rs-crm-wp.pkr.hcl
  provision-win2016_ad_sql2016_rs_crm_wp-terraform0:
    needs: build-win2016-ad-sql2016-rs-crm-wp
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.11.15
    env:
      TF_VAR_ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      TF_VAR_ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
      TF_VAR_MS_365_VMS_LOCATION: westeurope
      TF_VAR_MS_365_VMS_IMAGE_RG_NAME: CommonRGWestEurope
      TF_VAR_MS_365_VMS_VM_NAME_SPEC: swaz%s
      TF_VAR_MS_365_VMS_WIN2016_AD_SQL2016_RS_CRM_WP_IMAGE_ID: /subscriptions/86fab581-914f-4c91-be92-9a5d70691d54/resourceGroups/CommonRGWestEurope/providers/Microsoft.Compute/images/ms-365-vms-win2016-ad-sql2016-rs-crm-wp-westeurope-000000
      TF_VAR_MS_365_VMS_WIN2016_AD_SQL2016_RS_CRM_WP_VM_SIZE: Standard_B8ms
      TF_VAR_MS_365_VMS_DOMAIN_NAME: c0nt0s00.local
      TF_VAR_MS_365_VMS_VM_ADMIN_PASSWORD: ${{ secrets.MS_365_VMS_VM_ADMIN_PASSWORD }}
      TF_VAR_MS_365_VMS_DOMAIN_ADMIN_PASSWORD: ${{ secrets.MS_365_VMS_DOMAIN_ADMIN_PASSWORD }}
      TF_VAR_RS_SERVICE_PASSWORD: ${{ secrets.RS_SERVICE_PASSWORD }}
      TF_VAR_CRM_TEST_1_PASSWORD: ${{ secrets.CRM_TEST_1_PASSWORD }}
      TF_VAR_CRM_TEST_2_PASSWORD: ${{ secrets.CRM_TEST_2_PASSWORD }}
      TF_VAR_CRM_INSTALL_PASSWORD: ${{ secrets.CRM_INSTALL_PASSWORD }}
      TF_VAR_CRM_SERVICE_PASSWORD: ${{ secrets.CRM_SERVICE_PASSWORD }}
      TF_VAR_CRM_DEPLOYMENT_SERVICE_PASSWORD: ${{ secrets.CRM_DEPLOYMENT_SERVICE_PASSWORD }}
      TF_VAR_CRM_SANDBOX_SERVICE_PASSWORD: ${{ secrets.CRM_SANDBOX_SERVICE_PASSWORD }}
      TF_VAR_CRM_VSS_WRITER_PASSWORD: ${{ secrets.CRM_VSS_WRITER_PASSWORD }}
      TF_VAR_CRM_ASYNC_SERVICE_PASSWORD: ${{ secrets.CRM_ASYNC_SERVICE_PASSWORD }}
      TF_VAR_CRM_MONITORING_SERVICE_PASSWORD: ${{ secrets.CRM_MONITORING_SERVICE_PASSWORD }}
      TF_VAR_MS_365_VMS_SSL_CACHE_UNC: \\ms365vmswestdlrsv20.file.core.windows.net\common-00\certs-00
      TF_VAR_MS_365_VMS_SSL_CACHE_USERNAME: Azure\ms365vmswestdlrsv20
      TF_VAR_MS_365_VMS_SSL_CACHE_PASSWORD: ${{ secrets.MS_365_VMS_SSL_CACHE_PASSWORD }}
      TF_VAR_MS_365_VMS_SSL_PFX_PASSWORD: ${{ secrets.MS_365_VMS_SSL_PFX_PASSWORD }}
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_BASE: Dynamics365Server90RTMEnu
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_UPDATE: Dynamics365Server91Update16Enu
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_RE_UPDATE: Dynamics365Server91ReportingExtensionsUpdate16Enu
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_BASE_ISO_CURRENCY_CODE: USD
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_BASE_CURRENCY_NAME: US Dollar
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_BASE_CURRENCY_SYMBOL: $
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_BASE_CURRENCY_PRECISION: 2
      TF_VAR_MS_365_VMS_DYNAMICS_CRM_ORGANIZATION_COLLATION: Latin1_General_CI_AI
      TF_VAR_MS_365_VMS_STACK_INSTANCE_ID: ms-365-vms-win2016_ad_sql2016_rs_crm_wp-terraform0-tst00
      TF_VAR_MS_365_VMS_DNS_PREFIX: ms-365-vms-test-09-
    steps:
      - uses: actions/checkout@v3
      - run: cd infrastructure/stacks/azure/win2016_ad_sql2016_rs_crm_wp-terraform0; terraform init
      - run: cd infrastructure/stacks/azure/win2016_ad_sql2016_rs_crm_wp-terraform0; terraform workspace new $TF_VAR_MS_365_VMS_STACK_INSTANCE_ID
      - run: cd infrastructure/stacks/azure/win2016_ad_sql2016_rs_crm_wp-terraform0; terraform apply -auto-approve
  clean-win2016_ad_sql2016_rs_crm_wp-terraform0:
    if: ${{ always() }}
    needs: provision-win2016_ad_sql2016_rs_crm_wp-terraform0
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:2.48.1
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az group delete --subscription $ARM_SUBSCRIPTION_ID -n ms-365-vms-win2016_ad_sql2016_rs_crm_wp-terraform0-tst00 -y
  start-ms-365-vms-win2022_hyperv-ci-01:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:2.48.1
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az vm start --ids /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/ms-365-vms-win2022_hyperv-ci-01/providers/Microsoft.Compute/virtualMachines/swazserver00
  hyperv-prereqs-ms-365-vms-win2022_hyperv-ci-01:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-01'
      - 'wp00'
    needs: start-ms-365-vms-win2022_hyperv-ci-01
    steps:
      - run: |
          if (!(Get-VMSwitch -Name NATSwitch00 -ErrorAction Ignore)) {
            New-VMSwitch -SwitchName NATSwitch00 -SwitchType Internal;
            New-NetIPAddress -IPAddress 169.254.0.1 -PrefixLength 16 -InterfaceAlias "vEthernet (NATSwitch00)";
          }
          if (!(Get-NetNat -Name NATNetwork00 -ErrorAction Ignore)) {
            New-NetNAT -Name NATNetwork00 -InternalIPInterfaceAddressPrefix 169.254.0.0/16;
          }
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));
          choco install -y packer --version=1.8.7;
  remove-win2022-ad-sql2022-rs2019-crm-wp-image-hyperv:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-01'
      - 'wp00'
    needs: hyperv-prereqs-ms-365-vms-win2022_hyperv-ci-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          if (Get-Item infrastructure\images\output-win2022-ad-sql2022-rs2019-crm-wp-000000 -ErrorAction Ignore) {
            Remove-Item infrastructure\images\output-win2022-ad-sql2022-rs2019-crm-wp-000000 -Recurse
          }
          Remove-Item infrastructure\images\*.box
  build-win2022-ad-sql2022-rs2019-crm-wp-image-hyperv:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-01'
      - 'wp00'
    needs: remove-win2022-ad-sql2022-rs2019-crm-wp-image-hyperv
    env:
      MS_365_VMS_PROJECT_PREFIX: ms-365-vms-
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2022-ad-sql2022-rs2019-crm-wp-000000
      MS_365_VMS_HYPERV_SWITCH: NATSwitch00
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd infrastructure\images
          packer build -only hyperv-iso.* .\win2022-ad-sql2022-rs2019-crm-wp.pkr.hcl;
  deallocate-ms-365-vms-win2022_hyperv-ci-01:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build-win2022-ad-sql2022-rs2019-crm-wp-image-hyperv
    container:
      image: mcr.microsoft.com/azure-cli:2.48.1
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az vm deallocate --ids /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/ms-365-vms-win2022_hyperv-ci-01/providers/Microsoft.Compute/virtualMachines/swazserver00
  start-ms-365-vms-win2022_hyperv-ci-02:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:2.48.1
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az vm start --ids /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/ms-365-vms-win2022_hyperv-ci-02/providers/Microsoft.Compute/virtualMachines/swazserver00
  hyperv-prereqs-ms-365-vms-win2022_hyperv-ci-02:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-02'
      - 'wp00'
    needs: start-ms-365-vms-win2022_hyperv-ci-02
    steps:
      - run: |
          if (!(Get-VMSwitch -Name NATSwitch00 -ErrorAction Ignore)) {
            New-VMSwitch -SwitchName NATSwitch00 -SwitchType Internal;
            New-NetIPAddress -IPAddress 169.254.0.1 -PrefixLength 16 -InterfaceAlias "vEthernet (NATSwitch00)";
          }
          if (!(Get-NetNat -Name NATNetwork00 -ErrorAction Ignore)) {
            New-NetNAT -Name NATNetwork00 -InternalIPInterfaceAddressPrefix 169.254.0.0/16;
          }
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));
          choco install -y packer --version=1.8.7;
  remove-win2016-ad-sql2016-rs-crm-wp-image-hyperv:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-02'
      - 'wp00'
    needs: hyperv-prereqs-ms-365-vms-win2022_hyperv-ci-02
    steps:
      - uses: actions/checkout@v3
      - run: |
          if (Get-Item infrastructure\images\output-win2016-ad-sql2016-rs-crm-wp-000000 -ErrorAction Ignore) {
            Remove-Item infrastructure\images\output-win2016-ad-sql2016-rs-crm-wp-000000 -Recurse
          }
          Remove-Item infrastructure\images\*.box
  build-win2016-ad-sql2016-rs-crm-wp-image-hyperv:
    runs-on:
      - self-hosted
      - 'ms-365-vms-win2022_hyperv-ci-02'
      - 'wp00'
    needs: remove-win2016-ad-sql2016-rs-crm-wp-image-hyperv
    env:
      MS_365_VMS_PROJECT_PREFIX: ms-365-vms-
      MS_365_VMS_IMAGE_NAME: ms-365-vms-win2016-ad-sql2016-rs-crm-wp-000000
      MS_365_VMS_HYPERV_SWITCH: NATSwitch00
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd infrastructure\images
          packer build -only hyperv-iso.* .\win2016-ad-sql2016-rs-crm-wp.pkr.hcl;
  deallocate-ms-365-vms-win2022_hyperv-ci-02:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build-win2016-ad-sql2016-rs-crm-wp-image-hyperv
    container:
      image: mcr.microsoft.com/azure-cli:2.48.1
    env:
      ARM_CLIENT_ID: 59897406-8d0d-42c9-9fb5-9c9fa14c4e53
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 86fab581-914f-4c91-be92-9a5d70691d54
      ARM_TENANT_ID: 85173d93-99ef-4dff-9b45-495719659133
    steps:
      - run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
      - run: az vm deallocate --ids /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/ms-365-vms-win2022_hyperv-ci-02/providers/Microsoft.Compute/virtualMachines/swazserver00
